"""Versioned, exact-form lexicons for transparent title metrics."""

from __future__ import annotations

LEXICON_VERSION = "1.1"

# Forms are deliberately explicit: matching never stems or lemmatizes.
LEXICONS: dict[str, tuple[str, ...]] = {
    "legalese": (
        "act",
        "amend",
        "amended",
        "amending",
        "appropriation",
        "appropriations",
        "authorization",
        "authorize",
        "authorized",
        "code",
        "hereby",
        "notwithstanding",
        "provision",
        "provisions",
        "pursuant",
        "section",
        "subsection",
        "thereof",
        "title",
    ),
    "values_core": (
        "choice",
        "dignity",
        "fairness",
        "freedom",
        "justice",
        "liberty",
        "opportunity",
        "patriot",
        "prosperity",
        "rights",
    ),
    "values_contextual": (
        "american",
        "children",
        "community",
        "families",
        "family",
        "taxpayer",
        "taxpayers",
        "veteran",
        "veterans",
        "worker",
        "workers",
    ),
    "threat_core": (
        "abuse",
        "criminal",
        "crime",
        "crisis",
        "danger",
        "emergency",
        "fentanyl",
        "fraud",
        "illegal",
        "invasion",
        "risk",
        "terror",
        "terrorism",
        "threat",
        "trafficking",
        "violence",
    ),
    "threat_contextual": ("border", "security"),
    "mechanism_concrete": (
        "amend",
        "amended",
        "amending",
        "appropriate",
        "appropriated",
        "appropriates",
        "authorize",
        "authorized",
        "authorizes",
        "designate",
        "designated",
        "designates",
        "direct",
        "directed",
        "directs",
        "establish",
        "established",
        "establishes",
        "extend",
        "extended",
        "extends",
        "fund",
        "funded",
        "funding",
        "modify",
        "modified",
        "modifies",
        "prohibit",
        "prohibited",
        "prohibits",
        "provide",
        "provided",
        "provides",
        "repeal",
        "repealed",
        "repeals",
        "require",
        "required",
        "requires",
        "restrict",
        "restricted",
        "restricts",
    ),
    "broad_action": (
        "advance",
        "advanced",
        "advances",
        "defend",
        "defended",
        "defends",
        "improve",
        "improved",
        "improves",
        "modernize",
        "modernized",
        "modernizes",
        "preserve",
        "preserved",
        "preserves",
        "protect",
        "protected",
        "protects",
        "promote",
        "promoted",
        "promotes",
        "restore",
        "restored",
        "restores",
        "save",
        "saved",
        "saves",
        "secure",
        "secured",
        "secures",
        "strengthen",
        "strengthened",
        "strengthens",
        "support",
        "supported",
        "supports",
    ),
}

LEXICON_METADATA = {
    name: {"version": LEXICON_VERSION, "matching": "exact_curated_form"}
    for name in LEXICONS
}


def validate_lexicons() -> None:
    """Reject accidental overlap between core and contextual framing tiers."""
    for prefix in ("values", "threat"):
        overlap = set(LEXICONS[f"{prefix}_core"]) & set(
            LEXICONS[f"{prefix}_contextual"]
        )
        if overlap:
            raise ValueError(f"{prefix} core/contextual overlap: {sorted(overlap)}")


validate_lexicons()
