#!/bin/bash

(cat titles_all.txt | python preprocess.py 0 > intermediate-pos-files/0.txt) &
(cat titles_all.txt | python preprocess.py 1 > intermediate-pos-files/1.txt) &
(cat titles_all.txt | python preprocess.py 2 > intermediate-pos-files/2.txt) &
(cat titles_all.txt | python preprocess.py 3 > intermediate-pos-files/3.txt) &
(cat titles_all.txt | python preprocess.py 4 > intermediate-pos-files/4.txt) &
(cat titles_all.txt | python preprocess.py 5 > intermediate-pos-files/5.txt) &
(cat titles_all.txt | python preprocess.py 6 > intermediate-pos-files/6.txt) &
(cat titles_all.txt | python preprocess.py 7 > intermediate-pos-files/7.txt) &
(cat titles_all.txt | python preprocess.py 8 > intermediate-pos-files/8.txt) &
(cat titles_all.txt | python preprocess.py 9 > intermediate-pos-files/9.txt) &
(cat titles_all.txt | python preprocess.py 10 > intermediate-pos-files/10.txt) &
(cat titles_all.txt | python preprocess.py 11 > intermediate-pos-files/11.txt) &
(cat titles_all.txt | python preprocess.py 12 > intermediate-pos-files/12.txt) &
(cat titles_all.txt | python preprocess.py 13 > intermediate-pos-files/13.txt) &
(cat titles_all.txt | python preprocess.py 14 > intermediate-pos-files/14.txt) &
(cat titles_all.txt | python preprocess.py 15 > intermediate-pos-files/15.txt) &
(cat titles_all.txt | python preprocess.py 16 > intermediate-pos-files/16.txt) &
(cat titles_all.txt | python preprocess.py 17 > intermediate-pos-files/17.txt) &
(cat titles_all.txt | python preprocess.py 18 > intermediate-pos-files/18.txt) &
(cat titles_all.txt | python preprocess.py 19 > intermediate-pos-files/19.txt) &
(cat titles_all.txt | python preprocess.py 20 > intermediate-pos-files/20.txt) &
(cat titles_all.txt | python preprocess.py 21 > intermediate-pos-files/21.txt) &
(cat titles_all.txt | python preprocess.py 22 > intermediate-pos-files/22.txt) &
(cat titles_all.txt | python preprocess.py 23 > intermediate-pos-files/23.txt) &
(cat titles_all.txt | python preprocess.py 24 > intermediate-pos-files/24.txt) &
(cat titles_all.txt | python preprocess.py 25 > intermediate-pos-files/25.txt) &
(cat titles_all.txt | python preprocess.py 26 > intermediate-pos-files/26.txt) &
(cat titles_all.txt | python preprocess.py 27 > intermediate-pos-files/27.txt) &
(cat titles_all.txt | python preprocess.py 28 > intermediate-pos-files/28.txt) &
(cat titles_all.txt | python preprocess.py 29 > intermediate-pos-files/29.txt) &
(cat titles_all.txt | python preprocess.py 30 > intermediate-pos-files/30.txt) &
(cat titles_all.txt | python preprocess.py 31 > intermediate-pos-files/31.txt) &
(cat titles_all.txt | python preprocess.py 32 > intermediate-pos-files/32.txt) &
(cat titles_all.txt | python preprocess.py 33 > intermediate-pos-files/33.txt) &
(cat titles_all.txt | python preprocess.py 34 > intermediate-pos-files/34.txt) &
(cat titles_all.txt | python preprocess.py 35 > intermediate-pos-files/35.txt) &
(cat titles_all.txt | python preprocess.py 36 > intermediate-pos-files/36.txt) &
(cat titles_all.txt | python preprocess.py 37 > intermediate-pos-files/37.txt) &
(cat titles_all.txt | python preprocess.py 38 > intermediate-pos-files/38.txt) &
(cat titles_all.txt | python preprocess.py 39 > intermediate-pos-files/39.txt) &
(cat titles_all.txt | python preprocess.py 40 > intermediate-pos-files/40.txt) &
(cat titles_all.txt | python preprocess.py 41 > intermediate-pos-files/41.txt) &
(cat titles_all.txt | python preprocess.py 42 > intermediate-pos-files/42.txt) &
(cat titles_all.txt | python preprocess.py 43 > intermediate-pos-files/43.txt) &
(cat titles_all.txt | python preprocess.py 44 > intermediate-pos-files/44.txt) &
(cat titles_all.txt | python preprocess.py 45 > intermediate-pos-files/45.txt) &
(cat titles_all.txt | python preprocess.py 46 > intermediate-pos-files/46.txt) &
(cat titles_all.txt | python preprocess.py 47 > intermediate-pos-files/47.txt) &
(cat titles_all.txt | python preprocess.py 48 > intermediate-pos-files/48.txt) &
(cat titles_all.txt | python preprocess.py 49 > intermediate-pos-files/49.txt) &
(cat titles_all.txt | python preprocess.py 50 > intermediate-pos-files/50.txt) &
(cat titles_all.txt | python preprocess.py 51 > intermediate-pos-files/51.txt) &
(cat titles_all.txt | python preprocess.py 52 > intermediate-pos-files/52.txt) &
(cat titles_all.txt | python preprocess.py 53 > intermediate-pos-files/53.txt) &
(cat titles_all.txt | python preprocess.py 54 > intermediate-pos-files/54.txt) &
(cat titles_all.txt | python preprocess.py 55 > intermediate-pos-files/55.txt) &
(cat titles_all.txt | python preprocess.py 56 > intermediate-pos-files/56.txt) &
(cat titles_all.txt | python preprocess.py 57 > intermediate-pos-files/57.txt) &
(cat titles_all.txt | python preprocess.py 58 > intermediate-pos-files/58.txt) &
(cat titles_all.txt | python preprocess.py 59 > intermediate-pos-files/59.txt) &
(cat titles_all.txt | python preprocess.py 60 > intermediate-pos-files/60.txt) &
(cat titles_all.txt | python preprocess.py 61 > intermediate-pos-files/61.txt) &
(cat titles_all.txt | python preprocess.py 62 > intermediate-pos-files/62.txt) &
(cat titles_all.txt | python preprocess.py 63 > intermediate-pos-files/63.txt) &
(cat titles_all.txt | python preprocess.py 64 > intermediate-pos-files/64.txt) &
(cat titles_all.txt | python preprocess.py 65 > intermediate-pos-files/65.txt) &
(cat titles_all.txt | python preprocess.py 66 > intermediate-pos-files/66.txt) &
(cat titles_all.txt | python preprocess.py 67 > intermediate-pos-files/67.txt) &
(cat titles_all.txt | python preprocess.py 68 > intermediate-pos-files/68.txt) &
(cat titles_all.txt | python preprocess.py 69 > intermediate-pos-files/69.txt) &
(cat titles_all.txt | python preprocess.py 70 > intermediate-pos-files/70.txt) &
(cat titles_all.txt | python preprocess.py 71 > intermediate-pos-files/71.txt) &
(cat titles_all.txt | python preprocess.py 72 > intermediate-pos-files/72.txt) &
(cat titles_all.txt | python preprocess.py 73 > intermediate-pos-files/73.txt) &
(cat titles_all.txt | python preprocess.py 74 > intermediate-pos-files/74.txt) &
(cat titles_all.txt | python preprocess.py 75 > intermediate-pos-files/75.txt) &
(cat titles_all.txt | python preprocess.py 76 > intermediate-pos-files/76.txt) &
(cat titles_all.txt | python preprocess.py 77 > intermediate-pos-files/77.txt) &
(cat titles_all.txt | python preprocess.py 78 > intermediate-pos-files/78.txt) &
(cat titles_all.txt | python preprocess.py 79 > intermediate-pos-files/79.txt) &
(cat titles_all.txt | python preprocess.py 80 > intermediate-pos-files/80.txt) &
(cat titles_all.txt | python preprocess.py 81 > intermediate-pos-files/81.txt) &
(cat titles_all.txt | python preprocess.py 82 > intermediate-pos-files/82.txt) &
(cat titles_all.txt | python preprocess.py 83 > intermediate-pos-files/83.txt) &
(cat titles_all.txt | python preprocess.py 84 > intermediate-pos-files/84.txt) &
(cat titles_all.txt | python preprocess.py 85 > intermediate-pos-files/85.txt) &
(cat titles_all.txt | python preprocess.py 86 > intermediate-pos-files/86.txt) &
(cat titles_all.txt | python preprocess.py 87 > intermediate-pos-files/87.txt) &
(cat titles_all.txt | python preprocess.py 88 > intermediate-pos-files/88.txt) &
(cat titles_all.txt | python preprocess.py 89 > intermediate-pos-files/89.txt) &
(cat titles_all.txt | python preprocess.py 90 > intermediate-pos-files/90.txt) &
(cat titles_all.txt | python preprocess.py 91 > intermediate-pos-files/91.txt) &
(cat titles_all.txt | python preprocess.py 92 > intermediate-pos-files/92.txt) &
(cat titles_all.txt | python preprocess.py 93 > intermediate-pos-files/93.txt) &
(cat titles_all.txt | python preprocess.py 94 > intermediate-pos-files/94.txt) &
(cat titles_all.txt | python preprocess.py 95 > intermediate-pos-files/95.txt) &
(cat titles_all.txt | python preprocess.py 96 > intermediate-pos-files/96.txt) &
(cat titles_all.txt | python preprocess.py 97 > intermediate-pos-files/97.txt) &
(cat titles_all.txt | python preprocess.py 98 > intermediate-pos-files/98.txt) &
(cat titles_all.txt | python preprocess.py 99 > intermediate-pos-files/99.txt) &
(cat titles_all.txt | python preprocess.py 100 > intermediate-pos-files/100.txt) &
(cat titles_all.txt | python preprocess.py 101 > intermediate-pos-files/101.txt) &
(cat titles_all.txt | python preprocess.py 102 > intermediate-pos-files/102.txt) &
(cat titles_all.txt | python preprocess.py 103 > intermediate-pos-files/103.txt) &
(cat titles_all.txt | python preprocess.py 104 > intermediate-pos-files/104.txt) &
(cat titles_all.txt | python preprocess.py 105 > intermediate-pos-files/105.txt) &
(cat titles_all.txt | python preprocess.py 106 > intermediate-pos-files/106.txt) &
(cat titles_all.txt | python preprocess.py 107 > intermediate-pos-files/107.txt) &
(cat titles_all.txt | python preprocess.py 108 > intermediate-pos-files/108.txt) &
(cat titles_all.txt | python preprocess.py 109 > intermediate-pos-files/109.txt) &
(cat titles_all.txt | python preprocess.py 110 > intermediate-pos-files/110.txt) &
(cat titles_all.txt | python preprocess.py 111 > intermediate-pos-files/111.txt) &
(cat titles_all.txt | python preprocess.py 112 > intermediate-pos-files/112.txt) &
(cat titles_all.txt | python preprocess.py 113 > intermediate-pos-files/113.txt) &
(cat titles_all.txt | python preprocess.py 114 > intermediate-pos-files/114.txt) &
(cat titles_all.txt | python preprocess.py 115 > intermediate-pos-files/115.txt) &
(cat titles_all.txt | python preprocess.py 116 > intermediate-pos-files/116.txt) &
(cat titles_all.txt | python preprocess.py 117 > intermediate-pos-files/117.txt) &
(cat titles_all.txt | python preprocess.py 118 > intermediate-pos-files/118.txt) &
(cat titles_all.txt | python preprocess.py 119 > intermediate-pos-files/119.txt) &
(cat titles_all.txt | python preprocess.py 120 > intermediate-pos-files/120.txt) &
(cat titles_all.txt | python preprocess.py 121 > intermediate-pos-files/121.txt) &
(cat titles_all.txt | python preprocess.py 122 > intermediate-pos-files/122.txt) &
(cat titles_all.txt | python preprocess.py 123 > intermediate-pos-files/123.txt) &
(cat titles_all.txt | python preprocess.py 124 > intermediate-pos-files/124.txt) &
(cat titles_all.txt | python preprocess.py 125 > intermediate-pos-files/125.txt) &
(cat titles_all.txt | python preprocess.py 126 > intermediate-pos-files/126.txt) &
(cat titles_all.txt | python preprocess.py 127 > intermediate-pos-files/127.txt) &
(cat titles_all.txt | python preprocess.py 128 > intermediate-pos-files/128.txt) &
(cat titles_all.txt | python preprocess.py 129 > intermediate-pos-files/129.txt) &
(cat titles_all.txt | python preprocess.py 130 > intermediate-pos-files/130.txt) &
(cat titles_all.txt | python preprocess.py 131 > intermediate-pos-files/131.txt) &
(cat titles_all.txt | python preprocess.py 132 > intermediate-pos-files/132.txt) &
(cat titles_all.txt | python preprocess.py 133 > intermediate-pos-files/133.txt) &
(cat titles_all.txt | python preprocess.py 134 > intermediate-pos-files/134.txt) &
(cat titles_all.txt | python preprocess.py 135 > intermediate-pos-files/135.txt) &
(cat titles_all.txt | python preprocess.py 136 > intermediate-pos-files/136.txt) &
(cat titles_all.txt | python preprocess.py 137 > intermediate-pos-files/137.txt) &
(cat titles_all.txt | python preprocess.py 138 > intermediate-pos-files/138.txt) &
(cat titles_all.txt | python preprocess.py 139 > intermediate-pos-files/139.txt) &
(cat titles_all.txt | python preprocess.py 140 > intermediate-pos-files/140.txt) &
(cat titles_all.txt | python preprocess.py 141 > intermediate-pos-files/141.txt) &
(cat titles_all.txt | python preprocess.py 142 > intermediate-pos-files/142.txt) &
(cat titles_all.txt | python preprocess.py 143 > intermediate-pos-files/143.txt) &
(cat titles_all.txt | python preprocess.py 144 > intermediate-pos-files/144.txt) &
(cat titles_all.txt | python preprocess.py 145 > intermediate-pos-files/145.txt) &
(cat titles_all.txt | python preprocess.py 146 > intermediate-pos-files/146.txt) &
(cat titles_all.txt | python preprocess.py 147 > intermediate-pos-files/147.txt) &
(cat titles_all.txt | python preprocess.py 148 > intermediate-pos-files/148.txt) &
(cat titles_all.txt | python preprocess.py 149 > intermediate-pos-files/149.txt) &
(cat titles_all.txt | python preprocess.py 150 > intermediate-pos-files/150.txt) &
(cat titles_all.txt | python preprocess.py 151 > intermediate-pos-files/151.txt) &
(cat titles_all.txt | python preprocess.py 152 > intermediate-pos-files/152.txt) &
(cat titles_all.txt | python preprocess.py 153 > intermediate-pos-files/153.txt) &
(cat titles_all.txt | python preprocess.py 154 > intermediate-pos-files/154.txt) &
(cat titles_all.txt | python preprocess.py 155 > intermediate-pos-files/155.txt) &
(cat titles_all.txt | python preprocess.py 156 > intermediate-pos-files/156.txt) &
(cat titles_all.txt | python preprocess.py 157 > intermediate-pos-files/157.txt) &
(cat titles_all.txt | python preprocess.py 158 > intermediate-pos-files/158.txt) &
(cat titles_all.txt | python preprocess.py 159 > intermediate-pos-files/159.txt) &
(cat titles_all.txt | python preprocess.py 160 > intermediate-pos-files/160.txt) &
(cat titles_all.txt | python preprocess.py 161 > intermediate-pos-files/161.txt) &
(cat titles_all.txt | python preprocess.py 162 > intermediate-pos-files/162.txt) &
(cat titles_all.txt | python preprocess.py 163 > intermediate-pos-files/163.txt) &
(cat titles_all.txt | python preprocess.py 164 > intermediate-pos-files/164.txt) &
(cat titles_all.txt | python preprocess.py 165 > intermediate-pos-files/165.txt) &
(cat titles_all.txt | python preprocess.py 166 > intermediate-pos-files/166.txt) &
(cat titles_all.txt | python preprocess.py 167 > intermediate-pos-files/167.txt) &
(cat titles_all.txt | python preprocess.py 168 > intermediate-pos-files/168.txt) &
(cat titles_all.txt | python preprocess.py 169 > intermediate-pos-files/169.txt) &
(cat titles_all.txt | python preprocess.py 170 > intermediate-pos-files/170.txt) &
(cat titles_all.txt | python preprocess.py 171 > intermediate-pos-files/171.txt) &
(cat titles_all.txt | python preprocess.py 172 > intermediate-pos-files/172.txt) &
(cat titles_all.txt | python preprocess.py 173 > intermediate-pos-files/173.txt) &
(cat titles_all.txt | python preprocess.py 174 > intermediate-pos-files/174.txt) &
(cat titles_all.txt | python preprocess.py 175 > intermediate-pos-files/175.txt) &
(cat titles_all.txt | python preprocess.py 176 > intermediate-pos-files/176.txt) &
(cat titles_all.txt | python preprocess.py 177 > intermediate-pos-files/177.txt) &
(cat titles_all.txt | python preprocess.py 178 > intermediate-pos-files/178.txt) &
(cat titles_all.txt | python preprocess.py 179 > intermediate-pos-files/179.txt) &
(cat titles_all.txt | python preprocess.py 180 > intermediate-pos-files/180.txt) &
(cat titles_all.txt | python preprocess.py 181 > intermediate-pos-files/181.txt) &
(cat titles_all.txt | python preprocess.py 182 > intermediate-pos-files/182.txt) &
(cat titles_all.txt | python preprocess.py 183 > intermediate-pos-files/183.txt) &
(cat titles_all.txt | python preprocess.py 184 > intermediate-pos-files/184.txt) &
(cat titles_all.txt | python preprocess.py 185 > intermediate-pos-files/185.txt) &
(cat titles_all.txt | python preprocess.py 186 > intermediate-pos-files/186.txt) &
(cat titles_all.txt | python preprocess.py 187 > intermediate-pos-files/187.txt) &
(cat titles_all.txt | python preprocess.py 188 > intermediate-pos-files/188.txt) &
(cat titles_all.txt | python preprocess.py 189 > intermediate-pos-files/189.txt) &
(cat titles_all.txt | python preprocess.py 190 > intermediate-pos-files/190.txt) &
(cat titles_all.txt | python preprocess.py 191 > intermediate-pos-files/191.txt) &
(cat titles_all.txt | python preprocess.py 192 > intermediate-pos-files/192.txt) &
(cat titles_all.txt | python preprocess.py 193 > intermediate-pos-files/193.txt) &
(cat titles_all.txt | python preprocess.py 194 > intermediate-pos-files/194.txt) &
(cat titles_all.txt | python preprocess.py 195 > intermediate-pos-files/195.txt) &
(cat titles_all.txt | python preprocess.py 196 > intermediate-pos-files/196.txt) &
(cat titles_all.txt | python preprocess.py 197 > intermediate-pos-files/197.txt) &
(cat titles_all.txt | python preprocess.py 198 > intermediate-pos-files/198.txt) &
(cat titles_all.txt | python preprocess.py 199 > intermediate-pos-files/199.txt) &
(cat titles_all.txt | python preprocess.py 200 > intermediate-pos-files/200.txt) &
(cat titles_all.txt | python preprocess.py 201 > intermediate-pos-files/201.txt) &
(cat titles_all.txt | python preprocess.py 202 > intermediate-pos-files/202.txt) &
(cat titles_all.txt | python preprocess.py 203 > intermediate-pos-files/203.txt) &
(cat titles_all.txt | python preprocess.py 204 > intermediate-pos-files/204.txt) &
(cat titles_all.txt | python preprocess.py 205 > intermediate-pos-files/205.txt) &
(cat titles_all.txt | python preprocess.py 206 > intermediate-pos-files/206.txt) &
(cat titles_all.txt | python preprocess.py 207 > intermediate-pos-files/207.txt) &
(cat titles_all.txt | python preprocess.py 208 > intermediate-pos-files/208.txt) &
(cat titles_all.txt | python preprocess.py 209 > intermediate-pos-files/209.txt) &
(cat titles_all.txt | python preprocess.py 210 > intermediate-pos-files/210.txt) &
(cat titles_all.txt | python preprocess.py 211 > intermediate-pos-files/211.txt) &
(cat titles_all.txt | python preprocess.py 212 > intermediate-pos-files/212.txt) &
(cat titles_all.txt | python preprocess.py 213 > intermediate-pos-files/213.txt) &
(cat titles_all.txt | python preprocess.py 214 > intermediate-pos-files/214.txt) &
(cat titles_all.txt | python preprocess.py 215 > intermediate-pos-files/215.txt) &
(cat titles_all.txt | python preprocess.py 216 > intermediate-pos-files/216.txt) &
(cat titles_all.txt | python preprocess.py 217 > intermediate-pos-files/217.txt) &
(cat titles_all.txt | python preprocess.py 218 > intermediate-pos-files/218.txt) &
(cat titles_all.txt | python preprocess.py 219 > intermediate-pos-files/219.txt) &
(cat titles_all.txt | python preprocess.py 220 > intermediate-pos-files/220.txt) &
(cat titles_all.txt | python preprocess.py 221 > intermediate-pos-files/221.txt) &
(cat titles_all.txt | python preprocess.py 222 > intermediate-pos-files/222.txt) &
(cat titles_all.txt | python preprocess.py 223 > intermediate-pos-files/223.txt) &
(cat titles_all.txt | python preprocess.py 224 > intermediate-pos-files/224.txt) &
(cat titles_all.txt | python preprocess.py 225 > intermediate-pos-files/225.txt) &
(cat titles_all.txt | python preprocess.py 226 > intermediate-pos-files/226.txt) &
(cat titles_all.txt | python preprocess.py 227 > intermediate-pos-files/227.txt) &
(cat titles_all.txt | python preprocess.py 228 > intermediate-pos-files/228.txt) &
(cat titles_all.txt | python preprocess.py 229 > intermediate-pos-files/229.txt) &
(cat titles_all.txt | python preprocess.py 230 > intermediate-pos-files/230.txt) &
(cat titles_all.txt | python preprocess.py 231 > intermediate-pos-files/231.txt) &
(cat titles_all.txt | python preprocess.py 232 > intermediate-pos-files/232.txt) &
(cat titles_all.txt | python preprocess.py 233 > intermediate-pos-files/233.txt) &
(cat titles_all.txt | python preprocess.py 234 > intermediate-pos-files/234.txt) &
(cat titles_all.txt | python preprocess.py 235 > intermediate-pos-files/235.txt) &
(cat titles_all.txt | python preprocess.py 236 > intermediate-pos-files/236.txt) &
(cat titles_all.txt | python preprocess.py 237 > intermediate-pos-files/237.txt) &
(cat titles_all.txt | python preprocess.py 238 > intermediate-pos-files/238.txt) &
(cat titles_all.txt | python preprocess.py 239 > intermediate-pos-files/239.txt) &
(cat titles_all.txt | python preprocess.py 240 > intermediate-pos-files/240.txt) &
(cat titles_all.txt | python preprocess.py 241 > intermediate-pos-files/241.txt) &
(cat titles_all.txt | python preprocess.py 242 > intermediate-pos-files/242.txt) &
(cat titles_all.txt | python preprocess.py 243 > intermediate-pos-files/243.txt) &
(cat titles_all.txt | python preprocess.py 244 > intermediate-pos-files/244.txt) &
(cat titles_all.txt | python preprocess.py 245 > intermediate-pos-files/245.txt) &
(cat titles_all.txt | python preprocess.py 246 > intermediate-pos-files/246.txt) &
(cat titles_all.txt | python preprocess.py 247 > intermediate-pos-files/247.txt) &
(cat titles_all.txt | python preprocess.py 248 > intermediate-pos-files/248.txt) &
(cat titles_all.txt | python preprocess.py 249 > intermediate-pos-files/249.txt) &
(cat titles_all.txt | python preprocess.py 250 > intermediate-pos-files/250.txt) &
(cat titles_all.txt | python preprocess.py 251 > intermediate-pos-files/251.txt) &
(cat titles_all.txt | python preprocess.py 252 > intermediate-pos-files/252.txt) &
(cat titles_all.txt | python preprocess.py 253 > intermediate-pos-files/253.txt) &
(cat titles_all.txt | python preprocess.py 254 > intermediate-pos-files/254.txt) &
(cat titles_all.txt | python preprocess.py 255 > intermediate-pos-files/255.txt) &
(cat titles_all.txt | python preprocess.py 256 > intermediate-pos-files/256.txt) &
(cat titles_all.txt | python preprocess.py 257 > intermediate-pos-files/257.txt) &
(cat titles_all.txt | python preprocess.py 258 > intermediate-pos-files/258.txt) &
(cat titles_all.txt | python preprocess.py 259 > intermediate-pos-files/259.txt) &
(cat titles_all.txt | python preprocess.py 260 > intermediate-pos-files/260.txt) &
(cat titles_all.txt | python preprocess.py 261 > intermediate-pos-files/261.txt) &
(cat titles_all.txt | python preprocess.py 262 > intermediate-pos-files/262.txt) &
(cat titles_all.txt | python preprocess.py 263 > intermediate-pos-files/263.txt) &
(cat titles_all.txt | python preprocess.py 264 > intermediate-pos-files/264.txt) &
(cat titles_all.txt | python preprocess.py 265 > intermediate-pos-files/265.txt) &
(cat titles_all.txt | python preprocess.py 266 > intermediate-pos-files/266.txt) &
(cat titles_all.txt | python preprocess.py 267 > intermediate-pos-files/267.txt) &
(cat titles_all.txt | python preprocess.py 268 > intermediate-pos-files/268.txt) &
(cat titles_all.txt | python preprocess.py 269 > intermediate-pos-files/269.txt) &
(cat titles_all.txt | python preprocess.py 270 > intermediate-pos-files/270.txt) &
(cat titles_all.txt | python preprocess.py 271 > intermediate-pos-files/271.txt) &
(cat titles_all.txt | python preprocess.py 272 > intermediate-pos-files/272.txt) &
(cat titles_all.txt | python preprocess.py 273 > intermediate-pos-files/273.txt) &
(cat titles_all.txt | python preprocess.py 274 > intermediate-pos-files/274.txt) &
(cat titles_all.txt | python preprocess.py 275 > intermediate-pos-files/275.txt) &
(cat titles_all.txt | python preprocess.py 276 > intermediate-pos-files/276.txt) &
(cat titles_all.txt | python preprocess.py 277 > intermediate-pos-files/277.txt) &
(cat titles_all.txt | python preprocess.py 278 > intermediate-pos-files/278.txt) &
(cat titles_all.txt | python preprocess.py 279 > intermediate-pos-files/279.txt) &
(cat titles_all.txt | python preprocess.py 280 > intermediate-pos-files/280.txt) &
(cat titles_all.txt | python preprocess.py 281 > intermediate-pos-files/281.txt) &
(cat titles_all.txt | python preprocess.py 282 > intermediate-pos-files/282.txt) &
(cat titles_all.txt | python preprocess.py 283 > intermediate-pos-files/283.txt) &
(cat titles_all.txt | python preprocess.py 284 > intermediate-pos-files/284.txt) &
(cat titles_all.txt | python preprocess.py 285 > intermediate-pos-files/285.txt) &
(cat titles_all.txt | python preprocess.py 286 > intermediate-pos-files/286.txt) &
(cat titles_all.txt | python preprocess.py 287 > intermediate-pos-files/287.txt) &
(cat titles_all.txt | python preprocess.py 288 > intermediate-pos-files/288.txt) &
(cat titles_all.txt | python preprocess.py 289 > intermediate-pos-files/289.txt) &
(cat titles_all.txt | python preprocess.py 290 > intermediate-pos-files/290.txt) &
(cat titles_all.txt | python preprocess.py 291 > intermediate-pos-files/291.txt) &
(cat titles_all.txt | python preprocess.py 292 > intermediate-pos-files/292.txt) &
(cat titles_all.txt | python preprocess.py 293 > intermediate-pos-files/293.txt) &
(cat titles_all.txt | python preprocess.py 294 > intermediate-pos-files/294.txt) &
(cat titles_all.txt | python preprocess.py 295 > intermediate-pos-files/295.txt) &
(cat titles_all.txt | python preprocess.py 296 > intermediate-pos-files/296.txt) &
(cat titles_all.txt | python preprocess.py 297 > intermediate-pos-files/297.txt) &
(cat titles_all.txt | python preprocess.py 298 > intermediate-pos-files/298.txt) &
(cat titles_all.txt | python preprocess.py 299 > intermediate-pos-files/299.txt) &
(cat titles_all.txt | python preprocess.py 300 > intermediate-pos-files/300.txt) &
(cat titles_all.txt | python preprocess.py 301 > intermediate-pos-files/301.txt) &
(cat titles_all.txt | python preprocess.py 302 > intermediate-pos-files/302.txt) &
(cat titles_all.txt | python preprocess.py 303 > intermediate-pos-files/303.txt) &
(cat titles_all.txt | python preprocess.py 304 > intermediate-pos-files/304.txt) &
(cat titles_all.txt | python preprocess.py 305 > intermediate-pos-files/305.txt) &
(cat titles_all.txt | python preprocess.py 306 > intermediate-pos-files/306.txt) &
(cat titles_all.txt | python preprocess.py 307 > intermediate-pos-files/307.txt) &
(cat titles_all.txt | python preprocess.py 308 > intermediate-pos-files/308.txt) &
(cat titles_all.txt | python preprocess.py 309 > intermediate-pos-files/309.txt) &
(cat titles_all.txt | python preprocess.py 310 > intermediate-pos-files/310.txt) &
(cat titles_all.txt | python preprocess.py 311 > intermediate-pos-files/311.txt) &
(cat titles_all.txt | python preprocess.py 312 > intermediate-pos-files/312.txt) &
(cat titles_all.txt | python preprocess.py 313 > intermediate-pos-files/313.txt) &
(cat titles_all.txt | python preprocess.py 314 > intermediate-pos-files/314.txt) &
(cat titles_all.txt | python preprocess.py 315 > intermediate-pos-files/315.txt) &
(cat titles_all.txt | python preprocess.py 316 > intermediate-pos-files/316.txt) &
(cat titles_all.txt | python preprocess.py 317 > intermediate-pos-files/317.txt) &
(cat titles_all.txt | python preprocess.py 318 > intermediate-pos-files/318.txt) &
(cat titles_all.txt | python preprocess.py 319 > intermediate-pos-files/319.txt) &
(cat titles_all.txt | python preprocess.py 320 > intermediate-pos-files/320.txt) &
(cat titles_all.txt | python preprocess.py 321 > intermediate-pos-files/321.txt) &
(cat titles_all.txt | python preprocess.py 322 > intermediate-pos-files/322.txt) &
(cat titles_all.txt | python preprocess.py 323 > intermediate-pos-files/323.txt) &
(cat titles_all.txt | python preprocess.py 324 > intermediate-pos-files/324.txt) &
(cat titles_all.txt | python preprocess.py 325 > intermediate-pos-files/325.txt) &
(cat titles_all.txt | python preprocess.py 326 > intermediate-pos-files/326.txt) &
(cat titles_all.txt | python preprocess.py 327 > intermediate-pos-files/327.txt) &
(cat titles_all.txt | python preprocess.py 328 > intermediate-pos-files/328.txt) &
(cat titles_all.txt | python preprocess.py 329 > intermediate-pos-files/329.txt) &
(cat titles_all.txt | python preprocess.py 330 > intermediate-pos-files/330.txt) &
(cat titles_all.txt | python preprocess.py 331 > intermediate-pos-files/331.txt) &
(cat titles_all.txt | python preprocess.py 332 > intermediate-pos-files/332.txt) &
(cat titles_all.txt | python preprocess.py 333 > intermediate-pos-files/333.txt) &
(cat titles_all.txt | python preprocess.py 334 > intermediate-pos-files/334.txt) &
(cat titles_all.txt | python preprocess.py 335 > intermediate-pos-files/335.txt) &
(cat titles_all.txt | python preprocess.py 336 > intermediate-pos-files/336.txt) &
(cat titles_all.txt | python preprocess.py 337 > intermediate-pos-files/337.txt) &
(cat titles_all.txt | python preprocess.py 338 > intermediate-pos-files/338.txt) &
(cat titles_all.txt | python preprocess.py 339 > intermediate-pos-files/339.txt) &
(cat titles_all.txt | python preprocess.py 340 > intermediate-pos-files/340.txt) &
(cat titles_all.txt | python preprocess.py 341 > intermediate-pos-files/341.txt) &
(cat titles_all.txt | python preprocess.py 342 > intermediate-pos-files/342.txt) &
(cat titles_all.txt | python preprocess.py 343 > intermediate-pos-files/343.txt) &
(cat titles_all.txt | python preprocess.py 344 > intermediate-pos-files/344.txt) &
(cat titles_all.txt | python preprocess.py 345 > intermediate-pos-files/345.txt) &
(cat titles_all.txt | python preprocess.py 346 > intermediate-pos-files/346.txt) &
wait
